#ZC 1st Madlib project
print ("this is a madlib. i am going to ask you questions and you need to answer them")
verb1 = input("can you tell me a verb:  ")
family_member = input("can you name a family role(such as mother, brother, grandma etc):  ")
verb2 = input("name a verb:  ")
room = input("name a room in a house:  ")
verb3 = input("name a verb:  ")
verb4 = input("name a verb ending in ing:  ")
furnature = input("name a singular noun:  ")
verb5 = input("name a verb:  ")
food = input("name a food:  ")
verb6 = input("name a verb:  ")
furnature2 = input("name some furnature:  ")
adgetive1 = input("tell me a adgitive:  ")
verb7 = input("tell me a verb(or an event starting with get):  ") 
story = ("you " + verb1 + " up in the morning and " + verb2 + " out the window. you hear your " + family_member + " calling your name from the " + room + ". so you " + verb3 + " down the stairs and find them " + verb4 + " on the " + furnature + ". they stand up and " + verb5 + " you. you thank them before going to the " + room + " and smelling the incredible scent of " + food + ". you " + verb6 + " on the " + furnature2 + " and get ready to eat the " + food + ". it tasted " + adgetive1 + ". then you go outside and get ready to " + verb7)
print (story)
